apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openobserve-data-pvc
  namespace: openobserve
spec:
  #storageClassName: localpv-zfs-postgres
  storageClassName: local-storage
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
