apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: prometheus
data:
  prometheus.rules: |-
    groups: []
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers: []
    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep              
        - source_labels: [__meta_kubernetes_endpoint_node_name]
          target_label: instance
      - job_name: "rabbitmq"
        static_configs:
          #- targets: ["10.0.0.10:32002"]
          - targets: ["rabbitmq-0.rabbitmq-service.default:15692"]            
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.state:8080']
        #kubernetes_sd_configs:
        #- role: endpoints
        #relabel_configs:
        #- source_labels: [__meta_kubernetes_service_name]
        #  regex: kube-state-metrics
        #  action: keep
        #- action: labelmap
        #  regex: __meta_kubernetes_service_label_(.+)
        #- source_labels: [__meta_kubernetes_namespace]
        #  action: replace
        #  target_label: kubernetes_namespace
        #- source_labels: [__meta_kubernetes_service_name]
        #  action: replace
