apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  type: NodePort
  ports:
  - name: rabbitmq-nodeport
    nodePort: 32001 # Your desired port
    port: 5672
  selector:
    app.kubernetes.io/name: task-queue
    app.kubernetes.io/component: rabbitmq
