# local settings 
[Interface]
PrivateKey = 8GizpmF0z+tdxB292P8/d36WtN1hkqQ/vcbnT9ZJxlA=
Address = 10.1.0.10/32
ListenPort = 51821

# remote settings for Hub
[Peer]
PublicKey = x8IxpWKv8lRS/I1kTmYoG9+xnJ1tNAGECeJM+JAHY1c=
Endpoint = 141.21.51.14:51823
AllowedIPs = 10.1.0.1/32,10.0.0.10/32
#AllowedIPs = 10.1.0.2/32,10.0.0.0/24
#AllowedIPs = 10.1.0.0/24,10.0.0.0/24
#AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 30
