# local settings
[Interface]
PrivateKey = MCgjx1hKN2BXlHJwjKktVgBAY8ZzO24TYhtiiYGDFl4=
#Address = 10.1.0.100/32
Address = 10.1.1.1/32
ListenPort = 51820

PreUp = iptables -I FORWARD -p icmp -j LOG --log-prefix "[FW]: " --log-level 7
PostDown = iptables -D FORWARD -p icmp -j LOG --log-prefix "[FW]: " --log-level 7

[Peer]
PublicKey = x8IxpWKv8lRS/I1kTmYoG9+xnJ1tNAGECeJM+JAHY1c=
Endpoint = 141.21.51.14:51823
#AllowedIPs = 10.1.0.1/32,10.0.0.10/32
AllowedIPs = 10.1.0.1/32,10.0.0.10/32
#AllowedIPs = 10.1.0.0/16,10.0.0.10/32
PersistentKeepalive = 30

# Workers
[Peer]
PublicKey = 283QYBLj+qSF1f64Zx4QZ3S3+97l1AoMpsg+671ETT4=
#AllowedIPs = 10.1.0.101/32
AllowedIPs = 10.1.1.2/32
